services:
  web:
    build: .
    command: ./wait-for-db.sh db python3 manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file: .env
    # depends_on:
    #   - db

#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3307:3306"

# volumes:
#   db_data:
