# Generated by Django 5.1.6 on 2025-02-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpoint',
            name='code',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='SubDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_description', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_descriptions', to='books.descriptions')),
            ],
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='SubPoint',
        ),
    ]
