# Generated by Django 5.1.6 on 2025-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_subpoint_code_rename_book_books_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdescriptions',
            name='code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
