# Generated by Django 5.1.6 on 2025-03-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_codeset_books_author_books_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeset',
            old_name='name',
            new_name='code',
        ),
    ]
